### ISSUE TITLE
[BUG] Not able to query using index pattern name in opensearch dashboard 1.3

### ISSUE THREAD

**Issue by debraj-manna** [opensearch-project/OpenSearch-Dashboards#3648]
The issue has been discussed in [forum](https://forum.opensearch.org/t/after-upgrading-to-opensearch-1-3-from-elasticsearch-7-10-index-field-expecting-index-id/13415) first before posting as a bug here.

Steps followed 

1. We recently upgraded to Opensearch 1.3 from Elasticsearch 7.10 in AWS. 
2. After upgrading, we are observing that queries using index-pattern name is failing in opensearch. The same used to work fine in elasticsearch 7.10 engine in AWS. 

For example, below query is failing in Opensearch

```
https://<url>/_dashboards/app/discover#/?_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,key:legId.traceId,negate:!f,params:(query:'95c81169d7485467'),type:phrase),query:(match_phrase:(legId.traceId:'95c81169d7485467')))),index:air-leg,interval:auto,query:(language:kuery,query:''),sort:!())&_g=(refreshInterval:(pause:!t))
```
The above query works fine in elasticsearch. 

In Opensearch if we replace `index:air-leg` with the index pattern id like `index:f4bd2db0-c73b-11ed-89c4-cf7874960abe` then it works fine.

We also verified by creating a new index pattern via Opensearch Dashboard. Just to rule out any migration/upgrade-related issue. But there also we are not able to query using index pattern name.

**Comment by abbyhu2000** [comment]
@debraj-manna  Thanks for opening the issue! 

I am not sure this is a bug. Currently in the OpenSearch Dashboards application, the index pattern are all referring using their index pattern id. (not only discover plugin, same things in other plugins like vis builder, visualization, dashboards) Since we store the index pattern information by using their id in the `appState`, and we persist `appState` in the '_a' of the URL, thus using `index:f4bd2db0-c73b-11ed-89c4-cf7874960abe` instead of `index:air-leg` will work.

We also refer index pattern by their id instead of their title for saved objects.
<img width="696" alt="Screen Shot 2023-03-22 at 11 05 07 AM" src="https://user-images.githubusercontent.com/43937633/226997319-8fc9367c-7ad0-410e-bea5-dc6a8e70aecf.png">

cc @ashwin-pc since i saw you responded on the forum.

**Comment by debraj-manna** [comment]
I was also under the impression that moving to OpenSearch 1.3 will have at least all the features from the previous Kibana, elastic search.

**Comment by debraj-spotnana** [comment]
Is anything decided on whether this is a bug or not? If it is a bug will it be fixed in 1.3 release ?

**Comment by debraj-manna** [comment]
Cross-posting from the forum 

The issue is still not resolved. So for now I am getting the index-pattern id by querying opensearch dashboard and then using it in my query. 

To get the index-pattern id I am using a query like below

```
debrajmanna@debrajmanna-DX6QR261G3 java % curl -X GET "https://staging.com/_search?pretty" -H 'Content-Type: application/json' -d'
{
  "query": {
    "match": {
      "index-pattern.title": "air-leg"
    }
  },
  "_source": false
}'
```

After migration I am observing the above query returning two hits

```
...
"max_score" : 3.370884,
    "hits" : [
      {
        "_index" : ".kibana_3",
        "_type" : "_doc",
        "_id" : "index-pattern:air-leg",
        "_score" : 3.370884
      },
      {
        "_index" : ".kibana_2",
        "_type" : "_doc",
        "_id" : "index-pattern:air-leg",
        "_score" : 2.8771467
      }
    ]
```

If I create the index-pattern after migation then it returns a single hit something like below

```
"max_score" : 2.170884,
    "hits" : [
      {
        "_index" : ".kibana_2",
        "_type" : "_doc",
        "_id" : "index-pattern:f4bd2db0-c73b-11ed-89c4-cf7874960abe",
        "_score" : 2.170884
      }
    ]
```

Can someone let me know what is the logic behind creation of `.kibana_2` and `.kibana_3` indices?

**Comment by seraphjiang** [comment]
Thank you for reporting this issue. This issue has been open for a long time without recent activity, and OpenSearch Dashboards has since moved to the 3.x release line (currently 3.6, with 3.7 upcoming). The last supported 2.x release is 2.19.x.

We're closing this as part of a housekeeping effort to keep the backlog actionable. If this issue is still reproducible on a supported version (2.19.x or 3.x), please feel free to reopen this issue or file a new one with updated reproduction steps and version details.

We appreciate your contribution to OpenSearch!
