### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by AB027PS** [opensearch-project/OpenSearch-Dashboards#5711]
**Describe the bug**

When I go to discover, find some documents using an index pattern and then try to view surrounding documents of one of them, I get an error that says "Unable to fetch anchor document". This only happens to when the _id of the document contains a plus sign. If I substitute %2B for + in the URL in the new window, it works.

**To Reproduce**
1. Create an index and several documents for it whose _id will contain a plus sign.
2. Create an index pattern for your index.
3. Go to discover, select your index pattern and find a document.
4. Click on the magnifying glass sign next to a document and the view surrounding documents.

**Expected behavior**
A new window will open with surrounding documents

**OpenSearch Version**
2.11
Docker image 2.11.1

**Dashboards Version**
2.11
Docker image 2.11.1

**Plugins**

N/A

**Screenshots**

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/124600946/d1667421-5e62-47de-b4d7-88c5e414a2e7)
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/124600946/4e095841-fe32-45c6-99b6-2ee7042e6d67)

**Host/Environment (please complete the following information):**
 - OS: Linux
 - Browser and version 120.0.6099.218 (Official Build) (64-bit)

**Additional context**

**Comment by kavilla** [comment]
@abbyhu2000 can you check if this is being addressed already in 2.12 or still need to be fixed by 2.13

**Comment by kavilla** [comment]
This could be an issue with encoding and maybe will have to do a patch to fix this.

**Comment by abbyhu2000** [comment]
just confirmed: this is a regression of release 2.11 discover. Legacy discover does not have this bug. @kavilla @ananzh @ashwin-pc 


https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/7cba6e38-54a7-43c0-b67a-732ffa688ac1

**Comment by abbyhu2000** [comment]
Should fix this in 2.13

**Comment by ashwin-pc** [comment]
@AB027PS This should be fixed in the 2.12 release https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5776. Can you verify?

**Comment by AB027PS** [comment]
Hi @ashwin-pc I tried it with version 2.12 in Docker and the bug is still there.

**Comment by smortex** [comment]
Same issue seems to happen when the id has a `@` character (converted to `%40` in the address bar).

Replacing the `%40` with `@` seems to help as a workaround.
