### ISSUE TITLE
[BUG] Filters stored in saved search are not loaded

### ISSUE THREAD

**Issue by msoler8785** [opensearch-project/OpenSearch-Dashboards#8339]
**Describe the bug**

After upgrading to 2.17 none of my saved searches load the previously saved filters.  When I inspect the object, the filters are still stored there, but do not load.  I do not see any errors in the browser console. I have cleared browser cache and tried the latest Chrome, Edge, and Firefox browsers.

**To Reproduce**
1. Go to Discover
2. Add a filter
3. Save a new search
4. Click "New" search
5. Remove any filters from the page
6. Click "Open"
7. Open the search that was just saved
8. Observe all the filters are missing.

**Expected behavior**
When a search is saved, all of the configured filters are saved along with it.

**OpenSearch Version**
2.17

**Dashboards Version**
2.17

**Plugins**
[kibana-enhanced-table](https://github.com/fbaligand/kibana-enhanced-table)

**Screenshots**
N/A

**Host/Environment (please complete the following information):**
 - OS: Windows 11
 - Microsoft Edge: 129.0.2792.52 (Official build) (64-bit) 
 - Firefox 130.0.1 (64-bit)
 - Chrome 129.0.6668.70 (Official Build) (64-bit) (cohort: M129 Rollout) 

**Additional context**

Potentially related issues:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7677
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/8338

**Comment by Psych0meter** [comment]
Same problem here.
I also tried to restore an old version of a saved search through saved objects, filters are still not displayed (but seems to works)

Host/Environment (please complete the following information):

- OpenSearch and Dashboards 2.17.0
- OS: MacOS 15.0
- Chrome Version 129.0.6668.60 (Official Build) (arm64)

**Comment by jasonrojas** [comment]
I am seeing this as well on 2.17.0 - Viewing the document in the .kibana index shows that it is saved with the query filters in place. Tested on a 2.16.0 opensearch-dashboards pointed at the same cluster and did not see any issues.

**Comment by StefanStroebel** [comment]
Also experienceing the same. TO add to this when exporting the saved object the filter is saved in the object.

**Comment by cinhtau** [comment]
Thanks a lot for filing, this is quite severe. Already the 2nd major issue for my users after the date wrap disaster https://github.com/opensearch-project/OpenSearch-Dashboards/issues/8441. My user base is growingly frustrated with the UI changes or experience. 

I exported the saved object search, re-applied the filters in Dashboards v2.17 and save it.
I opened a private window, load the saved search and all filters vanished or not applied again. This make the product unusable. With more than 1000 saved searches, we have to try downgrade to 2.16 or use Dashboards v2.16 with OpenSearch v2.17.

**Comment by cinhtau** [comment]
Just tested the usage of Dashboards v2.16 with OpenSearch v2.17. It works, filters in saved search were properly applied.

**Comment by StefanStroebel** [comment]
We also downgraded Dashboards to v2.16 on Opensearch 2.16 code base.

**Comment by LDrago27** [comment]
Thanks for bringing this up. The above PR should fix the issues with filters.

**Comment by nerijus** [comment]
> Thanks for bringing this up. The above PR should fix the issues with filters.

Could you please backport the PR to 2.x, so that we can apply it and build the packages?

**Comment by cinhtau** [comment]
I tested OpenSearch Dashboards 2.18.0 with OpenSearch 2.17.0. It seems to be gone.

I repackaged it as 2.17.9 for my experiment. Going to let my users work with it for a week before fully upgrading to 2.18.

**Comment by LDrago27** [comment]
Hi folks, The fix for this issue has been adressed in this  PR https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8689 which has already been merged into main. Using

**Comment by ohenr** [comment]
can we have a new build for the Docker tag 2.17.1 then?

**Comment by iliuta** [comment]
Same here, this is annoying, especially because the 2.17 is on AWS already ...

**Comment by joneswac** [comment]
Is this in 2.17.1? We're still seeing the bug in that version.

**Comment by msoler8785** [comment]
@joneswac 
Yeah, I think that version is affected.  I upgraded to 2.18.0 and it works again.

**Comment by fire2** [comment]
Are there any plans to backport this to 2.17.x? That's the latest version available on AWS...

**Comment by iliuta** [comment]
> Are there any plans to backport this to 2.17.x? That's the latest version available on AWS...

I asked AWS support and they told me that they are sorry, but the fix will come with the next version. (We're used to be big customer of theirs).

I've been waiting for a couple of months to migrate from 2.15 to 2.17. And now, 2.17 is bugged. We'll have to wait for a few months as well? Do they even have non regression tests of the software they provide to the customers?!

**Comment by fire2** [comment]
Unfortunately they have not released it yet. I just tried OpenSearch_2_17_R20241112-P4  on a search domain and it does not contain the fix.

**Comment by pstast** [comment]
Unfortunately, that's how it is. This is a response from AWS support:

> Amazon OpenSearch Service is also aware of this and the internal team has indicated that a patch release to include the fix is scheduled for February 2025.

**Comment by caviliar** [comment]
We have also been affected by this for too long now. The latest patch `OpenSearch_2_17_R20241112-P4` hasn't fixed it.


I just tried disabling `state:storeInSessionStorage` under advanced settings and it appears that some shared searches are now working. This might help others until an actual fix is released.

**Comment by mmuth** [comment]
Still having this issue on AWS... Updated to `OpenSearch_2_17_R20241112-P5` meanwhile - and was previously notified by the support that a patch for the problem should have been contained in that patch package. Not sure now if I have a different problem or it is just "still there". Anyone else?

**Comment by pstast** [comment]
The problem persists even after the latest update. We were promised that the problem would be fixed during February, but it still hasn't.

**Comment by kliakos** [comment]
I also confirm that `OpenSearch_2_17_R20241112-P5` didn't fix the problem. Very disappointing.

**Comment by cheewai-bash** [comment]
In response to my ticket, AWS Support says OpenSearch 2.18 upgrade may be expected in end March. But, I forgot to ask which year.

**Comment by anirudha** [comment]
> Hi folks, The fix for this issue has been adressed in this  PR https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8689 which has already been merged into main. Using 

The primary issue reported in the bug was fixed 'here' and patched in the open source release.

**Comment by jacob-moulin** [comment]
Upgraded from `OpenSearch_2_17_R20241112-P4` to `OpenSearch_2_17_R20241112-P5` over the weekend in hopes that this would solve our issue with save searches, where filters were not clearing when moving from one saved search to another. Still experiencing the issue.

**Comment by viatcheslavmogilevsky** [comment]
Still experienced the issue in `OpenSearch_2_17_R20250319`  (region: `eu-west-1`): opening saved search doesn't apply it filters, data-range

**Comment by jacob-moulin** [comment]
To follow up, users have reported that the latest software update: OpenSearch_2_17_R20250403 fixed the issue in us-east-1!

**Comment by augustkang** [comment]
I've also confirmed that the issue is fixed in OpenSearch_2_17_R20250403 (ap-northeast-2). After updating, make sure to clear your browser cache.
